export  {HomePage} from "./Home/HomePage"
export  {CartPage} from "./Cart/CartPage"
export {ProductsList} from "./products/ProductsList"
export {ProductDetail} from "./products/ProductDetail"
export {DashboardPage} from "./Dashboard/DashboardPage"
export {Register} from "./register"
export {Login} from "./Login"
export {OrderPage} from "./Order/OrderPage"
export {PageNotFound}from "./PageNotFound"